### ISSUE TITLE
Pokerchips should stack to avoid item spam

### ISSUE THREAD

**Issue by Chuckleberry-Finn** [Chuckleberry-Finn/game-night#18]

**Comment by fed-cap24** [comment]
I believe this could be fixed by implementing the snap position method I mentioned in another issue, since one of the actions could be "Stack", and it could be applied to multiple things, like cards, pieces positions, etc.

**Comment by Chuckleberry-Finn** [comment]
16c8efd3090f12a9cbf68d0ac3e456cfd9d82fea
