### ISSUE TITLE
World board games do not align with pieces

### ISSUE THREAD

**Issue by fed-cap24** [Chuckleberry-Finn/game-night#19]
**Describe the bug**
Board games don't align with pieces.

**To Reproduce**
Place pieces on a board game (Chess for instance). The world model pieces reflect the board, but the board does not align with the pieces. there seems to be an offset with the world model origin of the board

**Possible solution**
A possible solution would be to have the board assembled for a game of chess, and then move the board model in blender until the board matches the positions after updating it, scaling it if needed.

**Comment by fed-cap24** [comment]
I tested moving around the pieces for the chess board and pieces, and managed to get a pretty accurate result syncing with the board.

Here are the modified files:

[Files.zip](https://github.com/Chuckleberry-Finn/game-night/files/12697186/Files.zip)

**Comment by Chuckleberry-Finn** [comment]
implemented: 357cfdd9f257cd4e635e76052b9d104535a26f30
