### ISSUE TITLE
Scaling for higher resolutions

### ISSUE THREAD

**Issue by AndrewC3011** [Chuckleberry-Finn/game-night#23]
**Is your feature request related to a problem? Please describe.**
Cards and other objects look small in 4K. Scaling should be introduced as a setting if possible.

**Describe the solution you'd like**
Ability to adjust the scaling on the UI used for the games. Independent from the Vanilla scaling feature if possible.

**Comment by Chuckleberry-Finn** [comment]
Looking into this possibility.

**Comment by genchadt** [comment]
![image](https://github.com/Chuckleberry-Finn/game-night/assets/62498018/335270a9-5c6b-448b-b4ef-7ffd170d8680)

**Comment by Chuckleberry-Finn** [comment]
> ![image](https://user-images.githubusercontent.com/62498018/281960280-335270a9-5c6b-448b-b4ef-7ffd170d8680.png)
> 
> Happening for us on ultrawide 1080p and 2k screens.

https://github.com/Chuckleberry-Finn/game-night/discussions/22

**Comment by genchadt** [comment]
> > Happening for us on ultrawide 1080p and 2k screens.
> 
> This is not a related issue. https://github.com/Chuckleberry-Finn/game-night/discussions/22

Sorry. Shall I resubmit as it's own issue?

**Comment by Chuckleberry-Finn** [comment]
> > > Happening for us on ultrawide 1080p and 2k screens.
> > 
> > 
> > This is not a related issue. #22
> 
> Sorry. Shall I resubmit as it's own issue?

No, click the link to the discussion question. It's an issue caused by settings in PZ.

**Comment by genchadt** [comment]
> > > > Happening for us on ultrawide 1080p and 2k screens.
> > > 
> > > 
> > > This is not a related issue. #22
> > 
> > Sorry. Shall I resubmit as it's own issue?
> 
> No, click the link to the discussion question. It's an issue caused by settings in PZ.

Thanks.
