### ISSUE TITLE
Could you make it that when you hover over a specific tile in Monopoly you can read what it's called? cause it's kinda hard to figure out what property is associated with which card, maybe also add descriptions to all the cards showing you how much each one is worth

### ISSUE THREAD

**Issue by PineNut98** [Chuckleberry-Finn/game-night#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PineNut98** [comment]
can you make it that when you hover over a tile in monopoly in the Game UI it tells you which property card is associated to which tile? and maybe how much they cost to buy etc in the inventory description

**Comment by Chuckleberry-Finn** [comment]
Can look into this next pass. Related to #10

**Comment by Chuckleberry-Finn** [comment]
![ProjectZomboid64_w1lKfhkpC9](https://github.com/Chuckleberry-Finn/game-night/assets/6071161/bb3f9b45-6022-4439-b654-76e61998c6e0)

This will be part of the next update.
