### ISSUE TITLE
Merging equipped card stack to inventory deck causes stack to break and become stuck

### ISSUE THREAD

**Issue by CuteMoonGod** [Chuckleberry-Finn/game-night#44]
**Describe the bug**
If you merge an equipped stack of cards into an existing deck of your inventory, the stack will correctly be merged into the larger deck, but also consume and destroy the stack item; this causes a number of problems for as long as the game thinks the stack item is still equipped, such as:

- The virtual hand inside the "play game" window flashing in and out of existence and generally being unusable; attempting to add to it also throws an error
- The held stack being unequippable via the right click menu (equipping another item **does** work and clears the hand out, from my testing so far)
- If you draw additional cards into the phantom held stack, they will sort of enter the held stack but, as the actual item doesn't exist, they will also cease to exist

**To Reproduce**
- Draw and equip a hand of cards; size irrelevant
- Drag the hand of cards inside your inventory onto a compatible deck in your inventory
- You should now still have the hand equipped, but without corresponding entry in the inventory
 
![grafik](https://github.com/Chuckleberry-Finn/game-night/assets/4323352/f3a402a3-dc22-4e46-b08b-b3080b7569d5)

In regards to the last point (additional cards into the phantom held stack)
Proceed as above; then, with the phantom held stack still equipped, draw additional cards into your hand (this appears to only work if you have the deck in your inventory)

**Expected behavior**
When merging a deck, the mod should preferably check if the hand is equipped and either block the action or unequip the held phantom item.

**Screenshots**

**Console logs:**
Log capturing the error stack
[console.txt](https://github.com/user-attachments/files/15836255/console.txt)

**Additional context**

**Comment by Chuckleberry-Finn** [comment]
Thanks, I'll fix this asap. 👍

**Comment by CuteMoonGod** [comment]
Also found out that the same type of error happens in the "play game" interface if you move a card from your virtual hand to a stack you're holding and searching

**Comment by Chuckleberry-Finn** [comment]
Just leaving this here for my self:
- make item being removed unequipped first (?)
